### ISSUE TITLE
Macro options?

### ISSUE THREAD

**Issue by Jaxan** [linjer/jekyll-katex#16]
Hi,

Thank you for this Jekyll plugin. It works really well so far. However, I tried adding macros to the configuration, like so:

```
katex:
  rendering_options:
    macros:
      - "\\Nat": "\\mathbb{N}"
```

I tried several variations with quotes and backslashes, but none of them works. Is it supported?

**Comment by linjer** [comment]
@Jaxan thanks for opening this issue. Only a few `rendering_options` are actually supported, and `macros` is currently not one of them. It looks like it should be fairly easy to add support for. I'll work on this as soon as I am returned from traveling abroad.

**Comment by dshemetov** [comment]
+1, would appreciate this feature.

**Comment by linjer** [comment]
@dshemetov @jaxan Thanks for bringing this back up. Do either of you have some examples of complex macros you want to provide? I want to make sure I understand the use case and test against them. 

Would something like the following in `yaml` work?

```yml
katex:
  js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
  rendering_options:
    # ...
    macros:
      "mymacro": "x^2"
      "fooMacro": "\frac{1}{x}"
```
